---
- hosts: localhost
  connection: local
  vars:
    image_name: yuji/debian
    container_name: debian01
  tasks:
     - name: check image
       local_action: shell docker images | awk '{print $1}' | grep '^{{image_name}}$'
       changed_when: false
       register: grep
       failed_when: grep.rc not in [0, 1]
     - name: docker build
       local_action: command docker build -t {{image_name}} .
       when: grep.rc == 1
     - name: docker ps
       local_action: shell docker ps --filter name={{container_name}} | wc -l
       changed_when: false
       register: wc
     - name: docker run
       local_action: command docker run -d --name {{container_name}} {{image_name}} tail -f /dev/null
       when: wc.stdout.find("2") != 0

- hosts: docker_host
  connection: docker
  tasks:
    - name: install packages
      apt: name={{item}} state=present
      with_items:
        - vim
        - curl
